baseURL = "https://francessergi.github.io/cvMarina2022/"
languageCode = "en-us"
defaultContentLanguage = "es"
theme = "almeida-cv"
title = "Marina Francés - CV"
publishDir = "../docs"


[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#009688"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 3
